name: Node.js Check

on: [push]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      
      - uses: actions/setup-node@v6
        with:
          node-version: '24'
      
      - name: Show versions
        run: |
          node --version
          npm --version
      
      - name: List files
        run: ls -la